job_name: CVES_EXPLOITS_WITH_DETAILS
source_URL_ExploitDB: https://raw.githubusercontent.com/offensive-security/exploitdb/master/files_exploits.csv
source_URL_CVE_EDB_XRef: https://cve.mitre.org/data/refs/refmap/source-EXPLOIT-DB.html
target_project: dcsgva-da-prd
target_bucket: dcsgva-da-prd-ai-notebook
target_blob: 01_RAW/CVES_EXPLOITS_WITH_DETAILS/CVES_EXPLOITS_WITH_DETAILS_%date.jsonl
blob_for_Mitre_CVE_Exploits: 01_RAW/MITRE_CVE_EXPLOITS/MITRE_CVE_EXPLOITS_%date.jsonl
blob_for_ExploitDB: 01_RAW/EXPLOITDB/EXPLOITDB_%date.jsonl