job_name: QID_TO_CVES
source_project: dcsgva-da-prd
source_bucket: dcsgva-da-prd-ai-notebook
source_blob: 02_INTERMEDIATE/QID_CVE_MAP
target_project: dcsgva-da-prd
target_bucket: dcsgva-da-prd-ai-notebook
target_blob: 02_INTERMEDIATE/QID_TO_CVES/QID_TO_CVES_%date.jsonl