job_name: CMDB_CAT_A_SERVERS

source_project: dcsgva-da-prd
source_bucket: dcsgva-da-prd-ai-notebook

cmdb_graph_blob: 02_INTERMEDIATE/CMDB_GRAPH/CMDB_GRAPH

target_project: dcsgva-da-prd
target_bucket: dcsgva-da-prd-ai-notebook
target_blob: 02_INTERMEDIATE/CMDB_CAT_A_SERVERS/CMDB_CAT_A_SERVERS_%date.jsonl
target_csv_blob: 02_INTERMEDIATE/CMDB_CAT_A_SERVERS/CMDB_CAT_A_SERVERS_%date.csv